# Configuration file for actionlint
# This file defines custom runner labels for GitHub-provided ARM runners

self-hosted-runner:
  # GitHub-provided ARM runner labels used in this repository
  labels:
    - ubuntu-22.04-arm
    - windows-11-arm
