name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch_to_run:
        description: 'Branch to run the workflow on'
        required: false
        default: 'main'
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-arm, windows-latest, windows-11-arm]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ (github.event_name == 'workflow_dispatch' && inputs.branch_to_run) || (github.event_name == 'pull_request' && github.head_ref) || github.ref_name }}
      - name: Install toolchain components
        run: rustup component add rustfmt clippy
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: cargo build --all-features --verbose
      - name: Run tests
        run: cargo test --all-features --verbose
